chore: Upgrade local & dev postgres to 18 (#264)
### Summary

Matches version deployed in external database service after upgrade.

Change in mount path due to error message on first boot with original
mount path:

Error: in 18+, these Docker images are configured to store database data
in a
format which is compatible with "pg_ctlcluster" (specifically, using
major-version-specific directory names). This better reflects how
       PostgreSQL itself works, and how upgrades are to be performed.

       See also https://github.com/docker-library/postgres/pull/1259

       Counter to that, there appears to be PostgreSQL data in:
         /var/lib/postgresql/data (unused mount/volume)

       This is usually the result of upgrading the Docker image without
upgrading the underlying database using "pg_upgrade" (which requires
both
       versions).

The suggested container configuration for 18+ is to place a single mount
       at /var/lib/postgresql which will then place PostgreSQL data in a
subdirectory, allowing usage of "pg_upgrade --link" without mount point
       boundary issues.

See https://github.com/docker-library/postgres/issues/37 for a (long)
       discussion around this process, and suggestions for how to do so.